version: "3"
services:
  paystand-mysql:
    #image: mysql:5
    build:
      context: database
    volumes:
      - "./data/mysql:/var/lib/mysql"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: nodejs2
      MYSQL_USER: paystand
      MYSQL_PASSWORD: paystand
    restart: always
    networks:
      - practice-ea
  nodeapp:
    depends_on:
      - paystand-mysql
    expose:
    - 3000
    restart: on-failure
    build:
      context: app
    environment:
      DATABASE_HOST: paystand-mysql
    networks:
      - practice-ea
  nginx:
    depends_on:
      - nodeapp
    ports:
    - 0.0.0.0:80:80
    - 0.0.0.0:443:443
    restart: on-failure
    build:
      context: nginx
    networks:
      - practice-ea
    volumes:
    - "./data/nginx:/etc/nginx/conf.d"
    - "./data/certbot/conf:/etc/letsencrypt"
    - "./data/certbot/www:/var/www/certbot"
    #command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
    - "./data/certbot/conf:/etc/letsencrypt"
    - "./data/certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  practice-ea: