version: "3"
services:
  paystand-mysql:
    build:
      context: database
    volumes:
      - "mysql:/var/lib/mysql"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: nodejs2
      MYSQL_USER: paystand
      MYSQL_PASSWORD: paystand
    restart: always
    networks:
      - practice-ea
  nodeapp:
    depends_on:
      - paystand-mysql
    expose:
    - 3000
    restart: on-failure
    build:
      context: app
    environment:
      DATABASE_HOST: paystand-mysql
    networks:
      - practice-ea
  nginx:
    depends_on:
      - nodeapp
    ports:
    - "80:80"
    - "443:443"
    restart: on-failure
    build:
      context: nginx
    networks:
      - practice-ea
    volumes:
    - "nginx:/etc/nginx/conf.d"
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    - ./data/certbot/lib:/var/lib/letsencrypt
    - ./data/certbot/log:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - practice-ea
networks:
  practice-ea:
    driver: bridge
volumes:
  nginx:
  mysql: