version: "3"
services:
  paystand-mysql:
    build:
      context: database
    image: localhost:5000/mysql
    volumes:
      - /docker/volumes/mysql:/var/lib/mysql
    expose:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: nodejs2
      MYSQL_USER: paystand
      MYSQL_PASSWORD: paystand
    restart: on-failure
    networks:
      - practice-ea
  nodeapp:
    depends_on:
      - paystand-mysql
    expose:
    - 3000
    restart: on-failure
    build:
      context: app
    image: localhost:5000/nodejsapp
    environment:
      DATABASE_HOST: paystand-mysql
    networks:
      - practice-ea
  nginx:
    depends_on:
      - nodeapp
    ports:
    - 80:80
    - 443:443
    restart: on-failure
    image: nginx:stable-alpine
    networks:
      - practice-ea
    volumes:
    - ./data/nginx:/etc/nginx/conf.d
    - /docker/volumes/certbot/conf:/etc/letsencrypt
    - /docker/volumes/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
    - /docker/volumes/certbot/conf:/etc/letsencrypt
    - /docker/volumes/certbot/www:/var/www/certbot
    - /docker/volumes/certbot/lib:/var/lib/letsencrypt
    - /docker/volumes/certbot/log:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - practice-ea
  # docker run -d --name jenkins -p 8000:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-alpine
networks:
  practice-ea:
    driver: bridge
