version: "3"
services:
  paystand-mysql:
    build:
      context: database
    volumes:
      - ./data/database:/var/lib/mysql
    expose:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: nodejs2
      MYSQL_USER: paystand
      MYSQL_PASSWORD: paystand
    restart: always
    networks:
      - practice-ea
  nodeapp:
    depends_on:
      - paystand-mysql
    expose:
    - 3000
    restart: on-failure
    build:
      context: app
    environment:
      DATABASE_HOST: paystand-mysql
    networks:
      - practice-ea
  nginx:
    depends_on:
      - nodeapp
    ports:
    - 8080:80
    - 8443:8443
    restart: on-failure
    image: nginx:stable-alpine
    networks:
      - practice-ea
    volumes:
    - ./data/nginx:/etc/nginx/conf.d
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    - ./data/certbot/lib:/var/lib/letsencrypt
    - ./data/certbot/log:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - practice-ea
  # docker run -d --name jenkins -p 8000:8080 -p 50000:50000 -v ./data/jenkins:/var/jenkins_home jenkins/jenkins:lts-alpine
  #jenkins:
  #  image: jenkins/jenkins:lts-alpine
  #  ports:
  #  - 8080:8080
  #  - 5000:5000
  #  volumes:
  #  - ./data/jenkins:/var/jenkins_home
  #  networks:
  #    - practice-ea
networks:
  practice-ea:
    driver: bridge
