version: "3"
services:
  cadvisor:
    image: google/cadvisor:latest
    expose:
    - 8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
    - /dev/disk:/dev/disk:ro
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
      - practice-ea
  grafana:
    depends_on:
      - prometheus
      - cadvisor
      - nodeexporter
      - nginxexporter
      - mysqlexporter
    image: grafana/grafana:latest
    volumes:
    - grafana:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
      - monitoring
  nodeexporter:
    image: prom/node-exporter:latest
    expose:
    - 9100
    networks:
      - monitoring
  nginxexporter:
    image: nginx/nginx-prometheus-exporter:latest
    entrypoint: "/usr/bin/exporter -nginx.scrape-uri http://nginx/nginx_status"
    expose:
    - 9113
    networks:
      - monitoring
      - practice-ea
  mysqlexporter:
    image: prom/mysqld-exporter:latest
    expose:
    - 9104
    environment:
      DATA_SOURCE_NAME: "paystand:paystand@(paystand-mysql:3306)/nodejs2"
    networks:
      - monitoring
      - practice-ea
  containerexporter:
    image: prom/container-exporter:latest
    expose:
    - 9104
    volumes:
    - /sys/fs/cgroup:/group
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge
  practice-ea:
    external:
      name: nodejs-mysql-crud_practice-ea
volumes:
  grafana:
