filebeat.inputs:
  #############################################
  # configuration for 7+ version
  #- type: container
  #  paths:
  #    - '/var/lib/docker/containers/*/*.log'
  #############################################
  # configuration for <= 6 version
  - type: docker
    containers:
      path: "/var/lib/docker/containers"
      stream: "stdout"
      ids:
        - "*"
  #############################################
processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.elasticsearch:
  hosts: ["elk:9200"]
  indices:
    - index: "filebeat-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
